// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypePatchCampaignCaptivePortalBrandingParams creates a new CustomerPrototypePatchCampaignCaptivePortalBrandingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypePatchCampaignCaptivePortalBrandingParams() *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	return &CustomerPrototypePatchCampaignCaptivePortalBrandingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypePatchCampaignCaptivePortalBrandingParamsWithTimeout creates a new CustomerPrototypePatchCampaignCaptivePortalBrandingParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypePatchCampaignCaptivePortalBrandingParamsWithTimeout(timeout time.Duration) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	return &CustomerPrototypePatchCampaignCaptivePortalBrandingParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypePatchCampaignCaptivePortalBrandingParamsWithContext creates a new CustomerPrototypePatchCampaignCaptivePortalBrandingParams object
// with the ability to set a context for a request.
func NewCustomerPrototypePatchCampaignCaptivePortalBrandingParamsWithContext(ctx context.Context) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	return &CustomerPrototypePatchCampaignCaptivePortalBrandingParams{
		Context: ctx,
	}
}

// NewCustomerPrototypePatchCampaignCaptivePortalBrandingParamsWithHTTPClient creates a new CustomerPrototypePatchCampaignCaptivePortalBrandingParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypePatchCampaignCaptivePortalBrandingParamsWithHTTPClient(client *http.Client) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	return &CustomerPrototypePatchCampaignCaptivePortalBrandingParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypePatchCampaignCaptivePortalBrandingParams contains all the parameters to send to the API endpoint

	for the customer prototype patch campaign captive portal branding operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypePatchCampaignCaptivePortalBrandingParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	//
	// Format: JSON
	LocationID string

	// NetworkID.
	NetworkID string

	// Payload.
	//
	// Format: JSON
	Payload *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype patch campaign captive portal branding params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithDefaults() *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype patch campaign captive portal branding params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithTimeout(timeout time.Duration) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithContext(ctx context.Context) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithHTTPClient(client *http.Client) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithID(id string) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithLocationID(locationID string) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithNetworkID adds the networkID to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithNetworkID(networkID string) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithPayload adds the payload to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WithPayload(payload *string) *CustomerPrototypePatchCampaignCaptivePortalBrandingParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the customer prototype patch campaign captive portal branding params
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) SetPayload(payload *string) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypePatchCampaignCaptivePortalBrandingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if o.Payload != nil {

		// form param payload
		var frPayload string
		if o.Payload != nil {
			frPayload = *o.Payload
		}
		fPayload := frPayload
		if fPayload != "" {
			if err := r.SetFormParam("payload", fPayload); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
