// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypeStartWpsParams creates a new CustomerPrototypeStartWpsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeStartWpsParams() *CustomerPrototypeStartWpsParams {
	return &CustomerPrototypeStartWpsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeStartWpsParamsWithTimeout creates a new CustomerPrototypeStartWpsParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeStartWpsParamsWithTimeout(timeout time.Duration) *CustomerPrototypeStartWpsParams {
	return &CustomerPrototypeStartWpsParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeStartWpsParamsWithContext creates a new CustomerPrototypeStartWpsParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeStartWpsParamsWithContext(ctx context.Context) *CustomerPrototypeStartWpsParams {
	return &CustomerPrototypeStartWpsParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeStartWpsParamsWithHTTPClient creates a new CustomerPrototypeStartWpsParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeStartWpsParamsWithHTTPClient(client *http.Client) *CustomerPrototypeStartWpsParams {
	return &CustomerPrototypeStartWpsParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeStartWpsParams contains all the parameters to send to the API endpoint

	for the customer prototype start wps operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeStartWpsParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// KeyID.
	//
	// Format: JSON
	KeyID *string

	// LocationID.
	//
	// Format: JSON
	LocationID string

	// NetworkID.
	NetworkID *string

	// NodeID.
	//
	// Format: JSON
	NodeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype start wps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeStartWpsParams) WithDefaults() *CustomerPrototypeStartWpsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype start wps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeStartWpsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithTimeout(timeout time.Duration) *CustomerPrototypeStartWpsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithContext(ctx context.Context) *CustomerPrototypeStartWpsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithHTTPClient(client *http.Client) *CustomerPrototypeStartWpsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithID(id string) *CustomerPrototypeStartWpsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetID(id string) {
	o.ID = id
}

// WithKeyID adds the keyID to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithKeyID(keyID *string) *CustomerPrototypeStartWpsParams {
	o.SetKeyID(keyID)
	return o
}

// SetKeyID adds the keyId to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetKeyID(keyID *string) {
	o.KeyID = keyID
}

// WithLocationID adds the locationID to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithLocationID(locationID string) *CustomerPrototypeStartWpsParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithNetworkID adds the networkID to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithNetworkID(networkID *string) *CustomerPrototypeStartWpsParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetNetworkID(networkID *string) {
	o.NetworkID = networkID
}

// WithNodeID adds the nodeID to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) WithNodeID(nodeID string) *CustomerPrototypeStartWpsParams {
	o.SetNodeID(nodeID)
	return o
}

// SetNodeID adds the nodeId to the customer prototype start wps params
func (o *CustomerPrototypeStartWpsParams) SetNodeID(nodeID string) {
	o.NodeID = nodeID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeStartWpsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.KeyID != nil {

		// form param keyId
		var frKeyID string
		if o.KeyID != nil {
			frKeyID = *o.KeyID
		}
		fKeyID := frKeyID
		if fKeyID != "" {
			if err := r.SetFormParam("keyId", fKeyID); err != nil {
				return err
			}
		}
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	if o.NetworkID != nil {

		// form param networkId
		var frNetworkID string
		if o.NetworkID != nil {
			frNetworkID = *o.NetworkID
		}
		fNetworkID := frNetworkID
		if fNetworkID != "" {
			if err := r.SetFormParam("networkId", fNetworkID); err != nil {
				return err
			}
		}
	}

	// form param nodeId
	frNodeID := o.NodeID
	fNodeID := frNodeID
	if fNodeID != "" {
		if err := r.SetFormParam("nodeId", fNodeID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
