// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypePutSnoozeOnDeviceAlertParams creates a new CustomerPrototypePutSnoozeOnDeviceAlertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypePutSnoozeOnDeviceAlertParams() *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	return &CustomerPrototypePutSnoozeOnDeviceAlertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypePutSnoozeOnDeviceAlertParamsWithTimeout creates a new CustomerPrototypePutSnoozeOnDeviceAlertParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypePutSnoozeOnDeviceAlertParamsWithTimeout(timeout time.Duration) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	return &CustomerPrototypePutSnoozeOnDeviceAlertParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypePutSnoozeOnDeviceAlertParamsWithContext creates a new CustomerPrototypePutSnoozeOnDeviceAlertParams object
// with the ability to set a context for a request.
func NewCustomerPrototypePutSnoozeOnDeviceAlertParamsWithContext(ctx context.Context) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	return &CustomerPrototypePutSnoozeOnDeviceAlertParams{
		Context: ctx,
	}
}

// NewCustomerPrototypePutSnoozeOnDeviceAlertParamsWithHTTPClient creates a new CustomerPrototypePutSnoozeOnDeviceAlertParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypePutSnoozeOnDeviceAlertParamsWithHTTPClient(client *http.Client) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	return &CustomerPrototypePutSnoozeOnDeviceAlertParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypePutSnoozeOnDeviceAlertParams contains all the parameters to send to the API endpoint

	for the customer prototype put snooze on device alert operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypePutSnoozeOnDeviceAlertParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	LocationID string

	/* Mac.

	   mac of device
	*/
	Mac string

	/* State.

	   enum of values include: snooze, ignore, performanceAcceptable
	*/
	State *string

	/* Type.

	   enum of values include: poorHealth
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype put snooze on device alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithDefaults() *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype put snooze on device alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithTimeout(timeout time.Duration) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithContext(ctx context.Context) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithHTTPClient(client *http.Client) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithID(id string) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithLocationID(locationID string) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithMac adds the mac to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithMac(mac string) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetMac(mac)
	return o
}

// SetMac adds the mac to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetMac(mac string) {
	o.Mac = mac
}

// WithState adds the state to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithState(state *string) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetState(state *string) {
	o.State = state
}

// WithType adds the typeVar to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WithType(typeVar string) *CustomerPrototypePutSnoozeOnDeviceAlertParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the customer prototype put snooze on device alert params
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypePutSnoozeOnDeviceAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// path param mac
	if err := r.SetPathParam("mac", o.Mac); err != nil {
		return err
	}

	if o.State != nil {

		// form param state
		var frState string
		if o.State != nil {
			frState = *o.State
		}
		fState := frState
		if fState != "" {
			if err := r.SetFormParam("state", fState); err != nil {
				return err
			}
		}
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
