// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams creates a new CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams() *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	return &CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParamsWithTimeout creates a new CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParamsWithTimeout(timeout time.Duration) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	return &CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParamsWithContext creates a new CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams object
// with the ability to set a context for a request.
func NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParamsWithContext(ctx context.Context) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	return &CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams{
		Context: ctx,
	}
}

// NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParamsWithHTTPClient creates a new CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParamsWithHTTPClient(client *http.Client) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	return &CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams contains all the parameters to send to the API endpoint

	for the customer prototype post location security policy o h p device setup operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	/* LanIPV4.

	   Mobile device lanIpv4 address, if any
	*/
	LanIPV4 *string

	/* LanIPV6.

	   Mobile device lanIpv6 address, if any
	*/
	LanIPV6 *string

	// LocationID.
	LocationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype post location security policy o h p device setup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithDefaults() *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype post location security policy o h p device setup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithTimeout(timeout time.Duration) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithContext(ctx context.Context) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithHTTPClient(client *http.Client) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithID(id string) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetID(id string) {
	o.ID = id
}

// WithLanIPV4 adds the lanIPV4 to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithLanIPV4(lanIPV4 *string) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetLanIPV4(lanIPV4)
	return o
}

// SetLanIPV4 adds the lanIpv4 to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetLanIPV4(lanIPV4 *string) {
	o.LanIPV4 = lanIPV4
}

// WithLanIPV6 adds the lanIPV6 to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithLanIPV6(lanIPV6 *string) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetLanIPV6(lanIPV6)
	return o
}

// SetLanIPV6 adds the lanIpv6 to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetLanIPV6(lanIPV6 *string) {
	o.LanIPV6 = lanIPV6
}

// WithLocationID adds the locationID to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WithLocationID(locationID string) *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype post location security policy o h p device setup params
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypePostLocationSecurityPolicyOHPDeviceSetupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.LanIPV4 != nil {

		// form param lanIpv4
		var frLanIPV4 string
		if o.LanIPV4 != nil {
			frLanIPV4 = *o.LanIPV4
		}
		fLanIPV4 := frLanIPV4
		if fLanIPV4 != "" {
			if err := r.SetFormParam("lanIpv4", fLanIPV4); err != nil {
				return err
			}
		}
	}

	if o.LanIPV6 != nil {

		// form param lanIpv6
		var frLanIPV6 string
		if o.LanIPV6 != nil {
			frLanIPV6 = *o.LanIPV6
		}
		fLanIPV6 := frLanIPV6
		if fLanIPV6 != "" {
			if err := r.SetFormParam("lanIpv6", fLanIPV6); err != nil {
				return err
			}
		}
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
