// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCustomerPrototypeGetLocationGuardEventsTldOrIPParams creates a new CustomerPrototypeGetLocationGuardEventsTldOrIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeGetLocationGuardEventsTldOrIPParams() *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	return &CustomerPrototypeGetLocationGuardEventsTldOrIPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeGetLocationGuardEventsTldOrIPParamsWithTimeout creates a new CustomerPrototypeGetLocationGuardEventsTldOrIPParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeGetLocationGuardEventsTldOrIPParamsWithTimeout(timeout time.Duration) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	return &CustomerPrototypeGetLocationGuardEventsTldOrIPParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeGetLocationGuardEventsTldOrIPParamsWithContext creates a new CustomerPrototypeGetLocationGuardEventsTldOrIPParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeGetLocationGuardEventsTldOrIPParamsWithContext(ctx context.Context) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	return &CustomerPrototypeGetLocationGuardEventsTldOrIPParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeGetLocationGuardEventsTldOrIPParamsWithHTTPClient creates a new CustomerPrototypeGetLocationGuardEventsTldOrIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeGetLocationGuardEventsTldOrIPParamsWithHTTPClient(client *http.Client) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	return &CustomerPrototypeGetLocationGuardEventsTldOrIPParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeGetLocationGuardEventsTldOrIPParams contains all the parameters to send to the API endpoint

	for the customer prototype get location guard events tld or Ip operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeGetLocationGuardEventsTldOrIPParams struct {

	/* EventTypes.

	   filter by event type, any combo of: 'adBlocking','teenagers','kids','adultAndSensitive','secureAndProtect','ipThreatOutbound','ipThreatInbound', 'iotProtect'. Returns all types by default.

	   Format: JSON
	*/
	EventTypes *string

	/* GroupOfUnassignedDevices.

	   to include the group of unassigned devices
	*/
	GroupOfUnassignedDevices *bool

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	LocationID string

	/* Macs.

	   array of macs[]

	   Format: JSON
	*/
	Macs *string

	/* Persons.

	   array of personIds[]

	   Format: JSON
	*/
	Persons *string

	/* ProtectionType.

	   filter by protectionType: ihp | ohp. Returns all types by default.
	*/
	ProtectionType *string

	/* TimePeriod.

	   Any of "last24Hours", "last7Days", "last30Days"

	   Default: "last30Days"
	*/
	TimePeriod *string

	/* TldOrIP.

	   top level domain or IP address
	*/
	TldOrIP *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype get location guard events tld or Ip params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithDefaults() *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype get location guard events tld or Ip params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetDefaults() {
	var (
		groupOfUnassignedDevicesDefault = bool(false)

		timePeriodDefault = string("last30Days")
	)

	val := CustomerPrototypeGetLocationGuardEventsTldOrIPParams{
		GroupOfUnassignedDevices: &groupOfUnassignedDevicesDefault,
		TimePeriod:               &timePeriodDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithTimeout(timeout time.Duration) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithContext(ctx context.Context) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithHTTPClient(client *http.Client) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventTypes adds the eventTypes to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithEventTypes(eventTypes *string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetEventTypes(eventTypes)
	return o
}

// SetEventTypes adds the eventTypes to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetEventTypes(eventTypes *string) {
	o.EventTypes = eventTypes
}

// WithGroupOfUnassignedDevices adds the groupOfUnassignedDevices to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithGroupOfUnassignedDevices(groupOfUnassignedDevices *bool) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetGroupOfUnassignedDevices(groupOfUnassignedDevices)
	return o
}

// SetGroupOfUnassignedDevices adds the groupOfUnassignedDevices to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetGroupOfUnassignedDevices(groupOfUnassignedDevices *bool) {
	o.GroupOfUnassignedDevices = groupOfUnassignedDevices
}

// WithID adds the id to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithID(id string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithLocationID(locationID string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithMacs adds the macs to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithMacs(macs *string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetMacs(macs)
	return o
}

// SetMacs adds the macs to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetMacs(macs *string) {
	o.Macs = macs
}

// WithPersons adds the persons to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithPersons(persons *string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetPersons(persons)
	return o
}

// SetPersons adds the persons to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetPersons(persons *string) {
	o.Persons = persons
}

// WithProtectionType adds the protectionType to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithProtectionType(protectionType *string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetProtectionType(protectionType)
	return o
}

// SetProtectionType adds the protectionType to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetProtectionType(protectionType *string) {
	o.ProtectionType = protectionType
}

// WithTimePeriod adds the timePeriod to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithTimePeriod(timePeriod *string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetTimePeriod(timePeriod)
	return o
}

// SetTimePeriod adds the timePeriod to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetTimePeriod(timePeriod *string) {
	o.TimePeriod = timePeriod
}

// WithTldOrIP adds the tldOrIP to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WithTldOrIP(tldOrIP *string) *CustomerPrototypeGetLocationGuardEventsTldOrIPParams {
	o.SetTldOrIP(tldOrIP)
	return o
}

// SetTldOrIP adds the tldOrIp to the customer prototype get location guard events tld or Ip params
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) SetTldOrIP(tldOrIP *string) {
	o.TldOrIP = tldOrIP
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeGetLocationGuardEventsTldOrIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EventTypes != nil {

		// form param eventTypes
		var frEventTypes string
		if o.EventTypes != nil {
			frEventTypes = *o.EventTypes
		}
		fEventTypes := frEventTypes
		if fEventTypes != "" {
			if err := r.SetFormParam("eventTypes", fEventTypes); err != nil {
				return err
			}
		}
	}

	if o.GroupOfUnassignedDevices != nil {

		// form param groupOfUnassignedDevices
		var frGroupOfUnassignedDevices bool
		if o.GroupOfUnassignedDevices != nil {
			frGroupOfUnassignedDevices = *o.GroupOfUnassignedDevices
		}
		fGroupOfUnassignedDevices := swag.FormatBool(frGroupOfUnassignedDevices)
		if fGroupOfUnassignedDevices != "" {
			if err := r.SetFormParam("groupOfUnassignedDevices", fGroupOfUnassignedDevices); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	if o.Macs != nil {

		// form param macs
		var frMacs string
		if o.Macs != nil {
			frMacs = *o.Macs
		}
		fMacs := frMacs
		if fMacs != "" {
			if err := r.SetFormParam("macs", fMacs); err != nil {
				return err
			}
		}
	}

	if o.Persons != nil {

		// form param persons
		var frPersons string
		if o.Persons != nil {
			frPersons = *o.Persons
		}
		fPersons := frPersons
		if fPersons != "" {
			if err := r.SetFormParam("persons", fPersons); err != nil {
				return err
			}
		}
	}

	if o.ProtectionType != nil {

		// form param protectionType
		var frProtectionType string
		if o.ProtectionType != nil {
			frProtectionType = *o.ProtectionType
		}
		fProtectionType := frProtectionType
		if fProtectionType != "" {
			if err := r.SetFormParam("protectionType", fProtectionType); err != nil {
				return err
			}
		}
	}

	if o.TimePeriod != nil {

		// form param timePeriod
		var frTimePeriod string
		if o.TimePeriod != nil {
			frTimePeriod = *o.TimePeriod
		}
		fTimePeriod := frTimePeriod
		if fTimePeriod != "" {
			if err := r.SetFormParam("timePeriod", fTimePeriod); err != nil {
				return err
			}
		}
	}

	if o.TldOrIP != nil {

		// form param tldOrIp
		var frTldOrIP string
		if o.TldOrIP != nil {
			frTldOrIP = *o.TldOrIP
		}
		fTldOrIP := frTldOrIP
		if fTldOrIP != "" {
			if err := r.SetFormParam("tldOrIp", fTldOrIP); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
