// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypePatchSubscriptionParams creates a new CustomerPrototypePatchSubscriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypePatchSubscriptionParams() *CustomerPrototypePatchSubscriptionParams {
	return &CustomerPrototypePatchSubscriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypePatchSubscriptionParamsWithTimeout creates a new CustomerPrototypePatchSubscriptionParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypePatchSubscriptionParamsWithTimeout(timeout time.Duration) *CustomerPrototypePatchSubscriptionParams {
	return &CustomerPrototypePatchSubscriptionParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypePatchSubscriptionParamsWithContext creates a new CustomerPrototypePatchSubscriptionParams object
// with the ability to set a context for a request.
func NewCustomerPrototypePatchSubscriptionParamsWithContext(ctx context.Context) *CustomerPrototypePatchSubscriptionParams {
	return &CustomerPrototypePatchSubscriptionParams{
		Context: ctx,
	}
}

// NewCustomerPrototypePatchSubscriptionParamsWithHTTPClient creates a new CustomerPrototypePatchSubscriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypePatchSubscriptionParamsWithHTTPClient(client *http.Client) *CustomerPrototypePatchSubscriptionParams {
	return &CustomerPrototypePatchSubscriptionParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypePatchSubscriptionParams contains all the parameters to send to the API endpoint

	for the customer prototype patch subscription operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypePatchSubscriptionParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	LocationID string

	/* Status.

	   enum of values include: Active, Suspended
	*/
	Status string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype patch subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePatchSubscriptionParams) WithDefaults() *CustomerPrototypePatchSubscriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype patch subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypePatchSubscriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) WithTimeout(timeout time.Duration) *CustomerPrototypePatchSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) WithContext(ctx context.Context) *CustomerPrototypePatchSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) WithHTTPClient(client *http.Client) *CustomerPrototypePatchSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) WithID(id string) *CustomerPrototypePatchSubscriptionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) WithLocationID(locationID string) *CustomerPrototypePatchSubscriptionParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithStatus adds the status to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) WithStatus(status string) *CustomerPrototypePatchSubscriptionParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the customer prototype patch subscription params
func (o *CustomerPrototypePatchSubscriptionParams) SetStatus(status string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypePatchSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// form param status
	frStatus := o.Status
	fStatus := frStatus
	if fStatus != "" {
		if err := r.SetFormParam("status", fStatus); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
