// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypePostCaptivePortalAuthorizedClientsReader is a Reader for the CustomerPrototypePostCaptivePortalAuthorizedClients structure.
type CustomerPrototypePostCaptivePortalAuthorizedClientsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerPrototypePostCaptivePortalAuthorizedClientsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypePostCaptivePortalAuthorizedClientsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypePostCaptivePortalAuthorizedClientsOK creates a CustomerPrototypePostCaptivePortalAuthorizedClientsOK with default headers values
func NewCustomerPrototypePostCaptivePortalAuthorizedClientsOK() *CustomerPrototypePostCaptivePortalAuthorizedClientsOK {
	return &CustomerPrototypePostCaptivePortalAuthorizedClientsOK{}
}

/*
CustomerPrototypePostCaptivePortalAuthorizedClientsOK describes a response with status code 200, with default header values.

Request was successful
*/
type CustomerPrototypePostCaptivePortalAuthorizedClientsOK struct {
	Payload interface{}
}

// IsSuccess returns true when this customer prototype post captive portal authorized clients o k response has a 2xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype post captive portal authorized clients o k response has a 3xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype post captive portal authorized clients o k response has a 4xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype post captive portal authorized clients o k response has a 5xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype post captive portal authorized clients o k response a status code equal to that given
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer prototype post captive portal authorized clients o k response
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) Code() int {
	return 200
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) Error() string {
	return fmt.Sprintf("[POST /Customers/{id}/locations/{locationId}/secondaryNetworks/captivePortals/{networkId}/authorizedClients][%d] customerPrototypePostCaptivePortalAuthorizedClientsOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) String() string {
	return fmt.Sprintf("[POST /Customers/{id}/locations/{locationId}/secondaryNetworks/captivePortals/{networkId}/authorizedClients][%d] customerPrototypePostCaptivePortalAuthorizedClientsOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerPrototypePostCaptivePortalAuthorizedClientsDefault creates a CustomerPrototypePostCaptivePortalAuthorizedClientsDefault with default headers values
func NewCustomerPrototypePostCaptivePortalAuthorizedClientsDefault(code int) *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault {
	return &CustomerPrototypePostCaptivePortalAuthorizedClientsDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypePostCaptivePortalAuthorizedClientsDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypePostCaptivePortalAuthorizedClientsDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype post captive portal authorized clients default response has a 2xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype post captive portal authorized clients default response has a 3xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype post captive portal authorized clients default response has a 4xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype post captive portal authorized clients default response has a 5xx status code
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype post captive portal authorized clients default response a status code equal to that given
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype post captive portal authorized clients default response
func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) Error() string {
	return fmt.Sprintf("[POST /Customers/{id}/locations/{locationId}/secondaryNetworks/captivePortals/{networkId}/authorizedClients][%d] Customer.prototype.postCaptivePortalAuthorizedClients default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) String() string {
	return fmt.Sprintf("[POST /Customers/{id}/locations/{locationId}/secondaryNetworks/captivePortals/{networkId}/authorizedClients][%d] Customer.prototype.postCaptivePortalAuthorizedClients default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypePostCaptivePortalAuthorizedClientsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
