// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypeDeleteKvConfigsParams creates a new CustomerPrototypeDeleteKvConfigsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeDeleteKvConfigsParams() *CustomerPrototypeDeleteKvConfigsParams {
	return &CustomerPrototypeDeleteKvConfigsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeDeleteKvConfigsParamsWithTimeout creates a new CustomerPrototypeDeleteKvConfigsParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeDeleteKvConfigsParamsWithTimeout(timeout time.Duration) *CustomerPrototypeDeleteKvConfigsParams {
	return &CustomerPrototypeDeleteKvConfigsParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeDeleteKvConfigsParamsWithContext creates a new CustomerPrototypeDeleteKvConfigsParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeDeleteKvConfigsParamsWithContext(ctx context.Context) *CustomerPrototypeDeleteKvConfigsParams {
	return &CustomerPrototypeDeleteKvConfigsParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeDeleteKvConfigsParamsWithHTTPClient creates a new CustomerPrototypeDeleteKvConfigsParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeDeleteKvConfigsParamsWithHTTPClient(client *http.Client) *CustomerPrototypeDeleteKvConfigsParams {
	return &CustomerPrototypeDeleteKvConfigsParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeDeleteKvConfigsParams contains all the parameters to send to the API endpoint

	for the customer prototype delete kv configs operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeDeleteKvConfigsParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// Key.
	Key string

	// LocationID.
	//
	// Format: JSON
	LocationID string

	// Module.
	Module string

	// NodeID.
	NodeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype delete kv configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeDeleteKvConfigsParams) WithDefaults() *CustomerPrototypeDeleteKvConfigsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype delete kv configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeDeleteKvConfigsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithTimeout(timeout time.Duration) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithContext(ctx context.Context) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithHTTPClient(client *http.Client) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithID(id string) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetID(id string) {
	o.ID = id
}

// WithKey adds the key to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithKey(key string) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetKey(key string) {
	o.Key = key
}

// WithLocationID adds the locationID to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithLocationID(locationID string) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithModule adds the module to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithModule(module string) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetModule(module)
	return o
}

// SetModule adds the module to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetModule(module string) {
	o.Module = module
}

// WithNodeID adds the nodeID to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) WithNodeID(nodeID string) *CustomerPrototypeDeleteKvConfigsParams {
	o.SetNodeID(nodeID)
	return o
}

// SetNodeID adds the nodeId to the customer prototype delete kv configs params
func (o *CustomerPrototypeDeleteKvConfigsParams) SetNodeID(nodeID string) {
	o.NodeID = nodeID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeDeleteKvConfigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// path param module
	if err := r.SetPathParam("module", o.Module); err != nil {
		return err
	}

	// path param nodeId
	if err := r.SetPathParam("nodeId", o.NodeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
