// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypeShareDeviceGroupReader is a Reader for the CustomerPrototypeShareDeviceGroup structure.
type CustomerPrototypeShareDeviceGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypeShareDeviceGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerPrototypeShareDeviceGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypeShareDeviceGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypeShareDeviceGroupOK creates a CustomerPrototypeShareDeviceGroupOK with default headers values
func NewCustomerPrototypeShareDeviceGroupOK() *CustomerPrototypeShareDeviceGroupOK {
	return &CustomerPrototypeShareDeviceGroupOK{}
}

/*
CustomerPrototypeShareDeviceGroupOK describes a response with status code 200, with default header values.

Request was successful
*/
type CustomerPrototypeShareDeviceGroupOK struct {
	Payload interface{}
}

// IsSuccess returns true when this customer prototype share device group o k response has a 2xx status code
func (o *CustomerPrototypeShareDeviceGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype share device group o k response has a 3xx status code
func (o *CustomerPrototypeShareDeviceGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype share device group o k response has a 4xx status code
func (o *CustomerPrototypeShareDeviceGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype share device group o k response has a 5xx status code
func (o *CustomerPrototypeShareDeviceGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype share device group o k response a status code equal to that given
func (o *CustomerPrototypeShareDeviceGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer prototype share device group o k response
func (o *CustomerPrototypeShareDeviceGroupOK) Code() int {
	return 200
}

func (o *CustomerPrototypeShareDeviceGroupOK) Error() string {
	return fmt.Sprintf("[PUT /Customers/{id}/locations/{locationId}/networkAccess/networks/{networkId}/deviceGroups/{groupId}/groupShares][%d] customerPrototypeShareDeviceGroupOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypeShareDeviceGroupOK) String() string {
	return fmt.Sprintf("[PUT /Customers/{id}/locations/{locationId}/networkAccess/networks/{networkId}/deviceGroups/{groupId}/groupShares][%d] customerPrototypeShareDeviceGroupOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypeShareDeviceGroupOK) GetPayload() interface{} {
	return o.Payload
}

func (o *CustomerPrototypeShareDeviceGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerPrototypeShareDeviceGroupDefault creates a CustomerPrototypeShareDeviceGroupDefault with default headers values
func NewCustomerPrototypeShareDeviceGroupDefault(code int) *CustomerPrototypeShareDeviceGroupDefault {
	return &CustomerPrototypeShareDeviceGroupDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypeShareDeviceGroupDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypeShareDeviceGroupDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype share device group default response has a 2xx status code
func (o *CustomerPrototypeShareDeviceGroupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype share device group default response has a 3xx status code
func (o *CustomerPrototypeShareDeviceGroupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype share device group default response has a 4xx status code
func (o *CustomerPrototypeShareDeviceGroupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype share device group default response has a 5xx status code
func (o *CustomerPrototypeShareDeviceGroupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype share device group default response a status code equal to that given
func (o *CustomerPrototypeShareDeviceGroupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype share device group default response
func (o *CustomerPrototypeShareDeviceGroupDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypeShareDeviceGroupDefault) Error() string {
	return fmt.Sprintf("[PUT /Customers/{id}/locations/{locationId}/networkAccess/networks/{networkId}/deviceGroups/{groupId}/groupShares][%d] Customer.prototype.shareDeviceGroup default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeShareDeviceGroupDefault) String() string {
	return fmt.Sprintf("[PUT /Customers/{id}/locations/{locationId}/networkAccess/networks/{networkId}/deviceGroups/{groupId}/groupShares][%d] Customer.prototype.shareDeviceGroup default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeShareDeviceGroupDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypeShareDeviceGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
