// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// NewCustomerPrototypeCreateAccessTokensParams creates a new CustomerPrototypeCreateAccessTokensParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeCreateAccessTokensParams() *CustomerPrototypeCreateAccessTokensParams {
	return &CustomerPrototypeCreateAccessTokensParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeCreateAccessTokensParamsWithTimeout creates a new CustomerPrototypeCreateAccessTokensParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeCreateAccessTokensParamsWithTimeout(timeout time.Duration) *CustomerPrototypeCreateAccessTokensParams {
	return &CustomerPrototypeCreateAccessTokensParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeCreateAccessTokensParamsWithContext creates a new CustomerPrototypeCreateAccessTokensParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeCreateAccessTokensParamsWithContext(ctx context.Context) *CustomerPrototypeCreateAccessTokensParams {
	return &CustomerPrototypeCreateAccessTokensParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeCreateAccessTokensParamsWithHTTPClient creates a new CustomerPrototypeCreateAccessTokensParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeCreateAccessTokensParamsWithHTTPClient(client *http.Client) *CustomerPrototypeCreateAccessTokensParams {
	return &CustomerPrototypeCreateAccessTokensParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeCreateAccessTokensParams contains all the parameters to send to the API endpoint

	for the customer prototype create access tokens operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeCreateAccessTokensParams struct {

	// Data.
	Data *models.AccessToken

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype create access tokens params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeCreateAccessTokensParams) WithDefaults() *CustomerPrototypeCreateAccessTokensParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype create access tokens params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeCreateAccessTokensParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) WithTimeout(timeout time.Duration) *CustomerPrototypeCreateAccessTokensParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) WithContext(ctx context.Context) *CustomerPrototypeCreateAccessTokensParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) WithHTTPClient(client *http.Client) *CustomerPrototypeCreateAccessTokensParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) WithData(data *models.AccessToken) *CustomerPrototypeCreateAccessTokensParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) SetData(data *models.AccessToken) {
	o.Data = data
}

// WithID adds the id to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) WithID(id string) *CustomerPrototypeCreateAccessTokensParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype create access tokens params
func (o *CustomerPrototypeCreateAccessTokensParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeCreateAccessTokensParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
