// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypeGetFrontHaulsDppParams creates a new CustomerPrototypeGetFrontHaulsDppParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeGetFrontHaulsDppParams() *CustomerPrototypeGetFrontHaulsDppParams {
	return &CustomerPrototypeGetFrontHaulsDppParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeGetFrontHaulsDppParamsWithTimeout creates a new CustomerPrototypeGetFrontHaulsDppParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeGetFrontHaulsDppParamsWithTimeout(timeout time.Duration) *CustomerPrototypeGetFrontHaulsDppParams {
	return &CustomerPrototypeGetFrontHaulsDppParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeGetFrontHaulsDppParamsWithContext creates a new CustomerPrototypeGetFrontHaulsDppParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeGetFrontHaulsDppParamsWithContext(ctx context.Context) *CustomerPrototypeGetFrontHaulsDppParams {
	return &CustomerPrototypeGetFrontHaulsDppParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeGetFrontHaulsDppParamsWithHTTPClient creates a new CustomerPrototypeGetFrontHaulsDppParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeGetFrontHaulsDppParamsWithHTTPClient(client *http.Client) *CustomerPrototypeGetFrontHaulsDppParams {
	return &CustomerPrototypeGetFrontHaulsDppParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeGetFrontHaulsDppParams contains all the parameters to send to the API endpoint

	for the customer prototype get front hauls dpp operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeGetFrontHaulsDppParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	//
	// Format: JSON
	LocationID string

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype get front hauls dpp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithDefaults() *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype get front hauls dpp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithTimeout(timeout time.Duration) *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithContext(ctx context.Context) *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithHTTPClient(client *http.Client) *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithID(id string) *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithLocationID(locationID string) *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithNetworkID adds the networkID to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) WithNetworkID(networkID string) *CustomerPrototypeGetFrontHaulsDppParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the customer prototype get front hauls dpp params
func (o *CustomerPrototypeGetFrontHaulsDppParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeGetFrontHaulsDppParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
