// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypePublishSlowChangingDimensionConfigsReader is a Reader for the CustomerPrototypePublishSlowChangingDimensionConfigs structure.
type CustomerPrototypePublishSlowChangingDimensionConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerPrototypePublishSlowChangingDimensionConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypePublishSlowChangingDimensionConfigsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypePublishSlowChangingDimensionConfigsOK creates a CustomerPrototypePublishSlowChangingDimensionConfigsOK with default headers values
func NewCustomerPrototypePublishSlowChangingDimensionConfigsOK() *CustomerPrototypePublishSlowChangingDimensionConfigsOK {
	return &CustomerPrototypePublishSlowChangingDimensionConfigsOK{}
}

/*
CustomerPrototypePublishSlowChangingDimensionConfigsOK describes a response with status code 200, with default header values.

Request was successful
*/
type CustomerPrototypePublishSlowChangingDimensionConfigsOK struct {
	Payload interface{}
}

// IsSuccess returns true when this customer prototype publish slow changing dimension configs o k response has a 2xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype publish slow changing dimension configs o k response has a 3xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype publish slow changing dimension configs o k response has a 4xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype publish slow changing dimension configs o k response has a 5xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype publish slow changing dimension configs o k response a status code equal to that given
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer prototype publish slow changing dimension configs o k response
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) Code() int {
	return 200
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) Error() string {
	return fmt.Sprintf("[POST /Customers/{id}/publishSlowChangingDimensionConfigs][%d] customerPrototypePublishSlowChangingDimensionConfigsOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) String() string {
	return fmt.Sprintf("[POST /Customers/{id}/publishSlowChangingDimensionConfigs][%d] customerPrototypePublishSlowChangingDimensionConfigsOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerPrototypePublishSlowChangingDimensionConfigsDefault creates a CustomerPrototypePublishSlowChangingDimensionConfigsDefault with default headers values
func NewCustomerPrototypePublishSlowChangingDimensionConfigsDefault(code int) *CustomerPrototypePublishSlowChangingDimensionConfigsDefault {
	return &CustomerPrototypePublishSlowChangingDimensionConfigsDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypePublishSlowChangingDimensionConfigsDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypePublishSlowChangingDimensionConfigsDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype publish slow changing dimension configs default response has a 2xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype publish slow changing dimension configs default response has a 3xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype publish slow changing dimension configs default response has a 4xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype publish slow changing dimension configs default response has a 5xx status code
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype publish slow changing dimension configs default response a status code equal to that given
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype publish slow changing dimension configs default response
func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) Error() string {
	return fmt.Sprintf("[POST /Customers/{id}/publishSlowChangingDimensionConfigs][%d] Customer.prototype.publishSlowChangingDimensionConfigs default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) String() string {
	return fmt.Sprintf("[POST /Customers/{id}/publishSlowChangingDimensionConfigs][%d] Customer.prototype.publishSlowChangingDimensionConfigs default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypePublishSlowChangingDimensionConfigsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
