// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypePatchOptimizationsReader is a Reader for the CustomerPrototypePatchOptimizations structure.
type CustomerPrototypePatchOptimizationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypePatchOptimizationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerPrototypePatchOptimizationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypePatchOptimizationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypePatchOptimizationsOK creates a CustomerPrototypePatchOptimizationsOK with default headers values
func NewCustomerPrototypePatchOptimizationsOK() *CustomerPrototypePatchOptimizationsOK {
	return &CustomerPrototypePatchOptimizationsOK{}
}

/*
CustomerPrototypePatchOptimizationsOK describes a response with status code 200, with default header values.

Request was successful
*/
type CustomerPrototypePatchOptimizationsOK struct {
	Payload *models.Optimizations
}

// IsSuccess returns true when this customer prototype patch optimizations o k response has a 2xx status code
func (o *CustomerPrototypePatchOptimizationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype patch optimizations o k response has a 3xx status code
func (o *CustomerPrototypePatchOptimizationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype patch optimizations o k response has a 4xx status code
func (o *CustomerPrototypePatchOptimizationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype patch optimizations o k response has a 5xx status code
func (o *CustomerPrototypePatchOptimizationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype patch optimizations o k response a status code equal to that given
func (o *CustomerPrototypePatchOptimizationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer prototype patch optimizations o k response
func (o *CustomerPrototypePatchOptimizationsOK) Code() int {
	return 200
}

func (o *CustomerPrototypePatchOptimizationsOK) Error() string {
	return fmt.Sprintf("[PATCH /Customers/{id}/locations/{locationId}/optimizations][%d] customerPrototypePatchOptimizationsOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypePatchOptimizationsOK) String() string {
	return fmt.Sprintf("[PATCH /Customers/{id}/locations/{locationId}/optimizations][%d] customerPrototypePatchOptimizationsOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypePatchOptimizationsOK) GetPayload() *models.Optimizations {
	return o.Payload
}

func (o *CustomerPrototypePatchOptimizationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Optimizations)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerPrototypePatchOptimizationsDefault creates a CustomerPrototypePatchOptimizationsDefault with default headers values
func NewCustomerPrototypePatchOptimizationsDefault(code int) *CustomerPrototypePatchOptimizationsDefault {
	return &CustomerPrototypePatchOptimizationsDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypePatchOptimizationsDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypePatchOptimizationsDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype patch optimizations default response has a 2xx status code
func (o *CustomerPrototypePatchOptimizationsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype patch optimizations default response has a 3xx status code
func (o *CustomerPrototypePatchOptimizationsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype patch optimizations default response has a 4xx status code
func (o *CustomerPrototypePatchOptimizationsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype patch optimizations default response has a 5xx status code
func (o *CustomerPrototypePatchOptimizationsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype patch optimizations default response a status code equal to that given
func (o *CustomerPrototypePatchOptimizationsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype patch optimizations default response
func (o *CustomerPrototypePatchOptimizationsDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypePatchOptimizationsDefault) Error() string {
	return fmt.Sprintf("[PATCH /Customers/{id}/locations/{locationId}/optimizations][%d] Customer.prototype.patchOptimizations default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypePatchOptimizationsDefault) String() string {
	return fmt.Sprintf("[PATCH /Customers/{id}/locations/{locationId}/optimizations][%d] Customer.prototype.patchOptimizations default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypePatchOptimizationsDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypePatchOptimizationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
