// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerPrototypeListCustomSharedSchedulesParams creates a new CustomerPrototypeListCustomSharedSchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeListCustomSharedSchedulesParams() *CustomerPrototypeListCustomSharedSchedulesParams {
	return &CustomerPrototypeListCustomSharedSchedulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeListCustomSharedSchedulesParamsWithTimeout creates a new CustomerPrototypeListCustomSharedSchedulesParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeListCustomSharedSchedulesParamsWithTimeout(timeout time.Duration) *CustomerPrototypeListCustomSharedSchedulesParams {
	return &CustomerPrototypeListCustomSharedSchedulesParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeListCustomSharedSchedulesParamsWithContext creates a new CustomerPrototypeListCustomSharedSchedulesParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeListCustomSharedSchedulesParamsWithContext(ctx context.Context) *CustomerPrototypeListCustomSharedSchedulesParams {
	return &CustomerPrototypeListCustomSharedSchedulesParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeListCustomSharedSchedulesParamsWithHTTPClient creates a new CustomerPrototypeListCustomSharedSchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeListCustomSharedSchedulesParamsWithHTTPClient(client *http.Client) *CustomerPrototypeListCustomSharedSchedulesParams {
	return &CustomerPrototypeListCustomSharedSchedulesParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeListCustomSharedSchedulesParams contains all the parameters to send to the API endpoint

	for the customer prototype list custom shared schedules operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeListCustomSharedSchedulesParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	//
	// Format: JSON
	LocationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype list custom shared schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WithDefaults() *CustomerPrototypeListCustomSharedSchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype list custom shared schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeListCustomSharedSchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WithTimeout(timeout time.Duration) *CustomerPrototypeListCustomSharedSchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WithContext(ctx context.Context) *CustomerPrototypeListCustomSharedSchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WithHTTPClient(client *http.Client) *CustomerPrototypeListCustomSharedSchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WithID(id string) *CustomerPrototypeListCustomSharedSchedulesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WithLocationID(locationID string) *CustomerPrototypeListCustomSharedSchedulesParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype list custom shared schedules params
func (o *CustomerPrototypeListCustomSharedSchedulesParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeListCustomSharedSchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
