// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypeGetPersonAppTimeCategoriesDataUsageReader is a Reader for the CustomerPrototypeGetPersonAppTimeCategoriesDataUsage structure.
type CustomerPrototypeGetPersonAppTimeCategoriesDataUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK creates a CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK with default headers values
func NewCustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK() *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK {
	return &CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK{}
}

/*
CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK describes a response with status code 200, with default header values.

Request was successful
*/
type CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK struct {
	Payload []interface{}
}

// IsSuccess returns true when this customer prototype get person app time categories data usage o k response has a 2xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype get person app time categories data usage o k response has a 3xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype get person app time categories data usage o k response has a 4xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype get person app time categories data usage o k response has a 5xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype get person app time categories data usage o k response a status code equal to that given
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer prototype get person app time categories data usage o k response
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) Code() int {
	return 200
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) Error() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/persons/{personId}/appTime/categories/dataUsage][%d] customerPrototypeGetPersonAppTimeCategoriesDataUsageOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) String() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/persons/{personId}/appTime/categories/dataUsage][%d] customerPrototypeGetPersonAppTimeCategoriesDataUsageOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault creates a CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault with default headers values
func NewCustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault(code int) *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault {
	return &CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype get person app time categories data usage default response has a 2xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype get person app time categories data usage default response has a 3xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype get person app time categories data usage default response has a 4xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype get person app time categories data usage default response has a 5xx status code
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype get person app time categories data usage default response a status code equal to that given
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype get person app time categories data usage default response
func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) Error() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/persons/{personId}/appTime/categories/dataUsage][%d] Customer.prototype.getPersonAppTimeCategoriesDataUsage default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) String() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/persons/{personId}/appTime/categories/dataUsage][%d] Customer.prototype.getPersonAppTimeCategoriesDataUsage default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypeGetPersonAppTimeCategoriesDataUsageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
