// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCustomerPrototypeGetLocationConfigAuditEventsParams creates a new CustomerPrototypeGetLocationConfigAuditEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeGetLocationConfigAuditEventsParams() *CustomerPrototypeGetLocationConfigAuditEventsParams {
	return &CustomerPrototypeGetLocationConfigAuditEventsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeGetLocationConfigAuditEventsParamsWithTimeout creates a new CustomerPrototypeGetLocationConfigAuditEventsParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeGetLocationConfigAuditEventsParamsWithTimeout(timeout time.Duration) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	return &CustomerPrototypeGetLocationConfigAuditEventsParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeGetLocationConfigAuditEventsParamsWithContext creates a new CustomerPrototypeGetLocationConfigAuditEventsParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeGetLocationConfigAuditEventsParamsWithContext(ctx context.Context) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	return &CustomerPrototypeGetLocationConfigAuditEventsParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeGetLocationConfigAuditEventsParamsWithHTTPClient creates a new CustomerPrototypeGetLocationConfigAuditEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeGetLocationConfigAuditEventsParamsWithHTTPClient(client *http.Client) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	return &CustomerPrototypeGetLocationConfigAuditEventsParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeGetLocationConfigAuditEventsParams contains all the parameters to send to the API endpoint

	for the customer prototype get location config audit events operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeGetLocationConfigAuditEventsParams struct {

	// Direction.
	Direction *string

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// Includes.
	//
	// Format: JSON
	Includes string

	// Limit.
	//
	// Format: double
	Limit *float64

	// LocationID.
	LocationID string

	// StartTime.
	//
	// Format: date-time
	StartTime strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype get location config audit events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithDefaults() *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype get location config audit events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithTimeout(timeout time.Duration) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithContext(ctx context.Context) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithHTTPClient(client *http.Client) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDirection adds the direction to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithDirection(direction *string) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetDirection(direction)
	return o
}

// SetDirection adds the direction to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetDirection(direction *string) {
	o.Direction = direction
}

// WithID adds the id to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithID(id string) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetID(id string) {
	o.ID = id
}

// WithIncludes adds the includes to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithIncludes(includes string) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetIncludes(includes)
	return o
}

// SetIncludes adds the includes to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetIncludes(includes string) {
	o.Includes = includes
}

// WithLimit adds the limit to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithLimit(limit *float64) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetLimit(limit *float64) {
	o.Limit = limit
}

// WithLocationID adds the locationID to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithLocationID(locationID string) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithStartTime adds the startTime to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WithStartTime(startTime strfmt.DateTime) *CustomerPrototypeGetLocationConfigAuditEventsParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the customer prototype get location config audit events params
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) SetStartTime(startTime strfmt.DateTime) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeGetLocationConfigAuditEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Direction != nil {

		// query param direction
		var qrDirection string

		if o.Direction != nil {
			qrDirection = *o.Direction
		}
		qDirection := qrDirection
		if qDirection != "" {

			if err := r.SetQueryParam("direction", qDirection); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param includes
	qrIncludes := o.Includes
	qIncludes := qrIncludes
	if qIncludes != "" {

		if err := r.SetQueryParam("includes", qIncludes); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit float64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatFloat64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// query param startTime
	qrStartTime := o.StartTime
	qStartTime := qrStartTime.String()
	if qStartTime != "" {

		if err := r.SetQueryParam("startTime", qStartTime); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
