// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistReader is a Reader for the CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelist structure.
type CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent creates a CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent with default headers values
func NewCustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent() *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent {
	return &CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent{}
}

/*
CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent describes a response with status code 204, with default header values.

Request was successful
*/
type CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent struct {
}

// IsSuccess returns true when this customer prototype delete from person security policy websites whitelist no content response has a 2xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype delete from person security policy websites whitelist no content response has a 3xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype delete from person security policy websites whitelist no content response has a 4xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype delete from person security policy websites whitelist no content response has a 5xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype delete from person security policy websites whitelist no content response a status code equal to that given
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the customer prototype delete from person security policy websites whitelist no content response
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) Code() int {
	return 204
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) Error() string {
	return fmt.Sprintf("[DELETE /Customers/{id}/locations/{locationId}/persons/{personId}/securityPolicy/websites/whitelist/{dns}][%d] customerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent ", 204)
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) String() string {
	return fmt.Sprintf("[DELETE /Customers/{id}/locations/{locationId}/persons/{personId}/securityPolicy/websites/whitelist/{dns}][%d] customerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent ", 204)
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault creates a CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault with default headers values
func NewCustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault(code int) *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault {
	return &CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype delete from person security policy websites whitelist default response has a 2xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype delete from person security policy websites whitelist default response has a 3xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype delete from person security policy websites whitelist default response has a 4xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype delete from person security policy websites whitelist default response has a 5xx status code
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype delete from person security policy websites whitelist default response a status code equal to that given
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype delete from person security policy websites whitelist default response
func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) Error() string {
	return fmt.Sprintf("[DELETE /Customers/{id}/locations/{locationId}/persons/{personId}/securityPolicy/websites/whitelist/{dns}][%d] Customer.prototype.deleteFromPersonSecurityPolicyWebsitesWhitelist default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) String() string {
	return fmt.Sprintf("[DELETE /Customers/{id}/locations/{locationId}/persons/{personId}/securityPolicy/websites/whitelist/{dns}][%d] Customer.prototype.deleteFromPersonSecurityPolicyWebsitesWhitelist default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypeDeleteFromPersonSecurityPolicyWebsitesWhitelistDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
