// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerLoginParams creates a new CustomerLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerLoginParams() *CustomerLoginParams {
	return &CustomerLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerLoginParamsWithTimeout creates a new CustomerLoginParams object
// with the ability to set a timeout on a request.
func NewCustomerLoginParamsWithTimeout(timeout time.Duration) *CustomerLoginParams {
	return &CustomerLoginParams{
		timeout: timeout,
	}
}

// NewCustomerLoginParamsWithContext creates a new CustomerLoginParams object
// with the ability to set a context for a request.
func NewCustomerLoginParamsWithContext(ctx context.Context) *CustomerLoginParams {
	return &CustomerLoginParams{
		Context: ctx,
	}
}

// NewCustomerLoginParamsWithHTTPClient creates a new CustomerLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerLoginParamsWithHTTPClient(client *http.Client) *CustomerLoginParams {
	return &CustomerLoginParams{
		HTTPClient: client,
	}
}

/*
CustomerLoginParams contains all the parameters to send to the API endpoint

	for the customer login operation.

	Typically these are written to a http.Request.
*/
type CustomerLoginParams struct {

	// Credentials.
	Credentials interface{}

	/* Include.

	   Related objects to include in the response. See the description of return value for more details.

	   Format: JSON
	*/
	Include *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerLoginParams) WithDefaults() *CustomerLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer login params
func (o *CustomerLoginParams) WithTimeout(timeout time.Duration) *CustomerLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer login params
func (o *CustomerLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer login params
func (o *CustomerLoginParams) WithContext(ctx context.Context) *CustomerLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer login params
func (o *CustomerLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer login params
func (o *CustomerLoginParams) WithHTTPClient(client *http.Client) *CustomerLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer login params
func (o *CustomerLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredentials adds the credentials to the customer login params
func (o *CustomerLoginParams) WithCredentials(credentials interface{}) *CustomerLoginParams {
	o.SetCredentials(credentials)
	return o
}

// SetCredentials adds the credentials to the customer login params
func (o *CustomerLoginParams) SetCredentials(credentials interface{}) {
	o.Credentials = credentials
}

// WithInclude adds the include to the customer login params
func (o *CustomerLoginParams) WithInclude(include *string) *CustomerLoginParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the customer login params
func (o *CustomerLoginParams) SetInclude(include *string) {
	o.Include = include
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Credentials != nil {
		if err := r.SetBodyParam(o.Credentials); err != nil {
			return err
		}
	}

	if o.Include != nil {

		// query param include
		var qrInclude string

		if o.Include != nil {
			qrInclude = *o.Include
		}
		qInclude := qrInclude
		if qInclude != "" {

			if err := r.SetQueryParam("include", qInclude); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
