// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// CustomerPrototypeGetTopologyReader is a Reader for the CustomerPrototypeGetTopology structure.
type CustomerPrototypeGetTopologyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerPrototypeGetTopologyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerPrototypeGetTopologyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerPrototypeGetTopologyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerPrototypeGetTopologyOK creates a CustomerPrototypeGetTopologyOK with default headers values
func NewCustomerPrototypeGetTopologyOK() *CustomerPrototypeGetTopologyOK {
	return &CustomerPrototypeGetTopologyOK{}
}

/*
CustomerPrototypeGetTopologyOK describes a response with status code 200, with default header values.

Request was successful
*/
type CustomerPrototypeGetTopologyOK struct {
	Payload *models.TopologyResponse
}

// IsSuccess returns true when this customer prototype get topology o k response has a 2xx status code
func (o *CustomerPrototypeGetTopologyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer prototype get topology o k response has a 3xx status code
func (o *CustomerPrototypeGetTopologyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer prototype get topology o k response has a 4xx status code
func (o *CustomerPrototypeGetTopologyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer prototype get topology o k response has a 5xx status code
func (o *CustomerPrototypeGetTopologyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer prototype get topology o k response a status code equal to that given
func (o *CustomerPrototypeGetTopologyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer prototype get topology o k response
func (o *CustomerPrototypeGetTopologyOK) Code() int {
	return 200
}

func (o *CustomerPrototypeGetTopologyOK) Error() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/topology][%d] customerPrototypeGetTopologyOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypeGetTopologyOK) String() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/topology][%d] customerPrototypeGetTopologyOK  %+v", 200, o.Payload)
}

func (o *CustomerPrototypeGetTopologyOK) GetPayload() *models.TopologyResponse {
	return o.Payload
}

func (o *CustomerPrototypeGetTopologyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TopologyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerPrototypeGetTopologyDefault creates a CustomerPrototypeGetTopologyDefault with default headers values
func NewCustomerPrototypeGetTopologyDefault(code int) *CustomerPrototypeGetTopologyDefault {
	return &CustomerPrototypeGetTopologyDefault{
		_statusCode: code,
	}
}

/*
CustomerPrototypeGetTopologyDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CustomerPrototypeGetTopologyDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this customer prototype get topology default response has a 2xx status code
func (o *CustomerPrototypeGetTopologyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer prototype get topology default response has a 3xx status code
func (o *CustomerPrototypeGetTopologyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer prototype get topology default response has a 4xx status code
func (o *CustomerPrototypeGetTopologyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer prototype get topology default response has a 5xx status code
func (o *CustomerPrototypeGetTopologyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer prototype get topology default response a status code equal to that given
func (o *CustomerPrototypeGetTopologyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer prototype get topology default response
func (o *CustomerPrototypeGetTopologyDefault) Code() int {
	return o._statusCode
}

func (o *CustomerPrototypeGetTopologyDefault) Error() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/topology][%d] Customer.prototype.getTopology default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeGetTopologyDefault) String() string {
	return fmt.Sprintf("[GET /Customers/{id}/locations/{locationId}/topology][%d] Customer.prototype.getTopology default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerPrototypeGetTopologyDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CustomerPrototypeGetTopologyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
