// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// NewCustomerPrototypeApproveDevicesParams creates a new CustomerPrototypeApproveDevicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPrototypeApproveDevicesParams() *CustomerPrototypeApproveDevicesParams {
	return &CustomerPrototypeApproveDevicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPrototypeApproveDevicesParamsWithTimeout creates a new CustomerPrototypeApproveDevicesParams object
// with the ability to set a timeout on a request.
func NewCustomerPrototypeApproveDevicesParamsWithTimeout(timeout time.Duration) *CustomerPrototypeApproveDevicesParams {
	return &CustomerPrototypeApproveDevicesParams{
		timeout: timeout,
	}
}

// NewCustomerPrototypeApproveDevicesParamsWithContext creates a new CustomerPrototypeApproveDevicesParams object
// with the ability to set a context for a request.
func NewCustomerPrototypeApproveDevicesParamsWithContext(ctx context.Context) *CustomerPrototypeApproveDevicesParams {
	return &CustomerPrototypeApproveDevicesParams{
		Context: ctx,
	}
}

// NewCustomerPrototypeApproveDevicesParamsWithHTTPClient creates a new CustomerPrototypeApproveDevicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPrototypeApproveDevicesParamsWithHTTPClient(client *http.Client) *CustomerPrototypeApproveDevicesParams {
	return &CustomerPrototypeApproveDevicesParams{
		HTTPClient: client,
	}
}

/*
CustomerPrototypeApproveDevicesParams contains all the parameters to send to the API endpoint

	for the customer prototype approve devices operation.

	Typically these are written to a http.Request.
*/
type CustomerPrototypeApproveDevicesParams struct {

	/* ID.

	   Customer id

	   Format: JSON
	*/
	ID string

	// LocationID.
	LocationID string

	// Macs.
	Macs []models.XAny

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer prototype approve devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeApproveDevicesParams) WithDefaults() *CustomerPrototypeApproveDevicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer prototype approve devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPrototypeApproveDevicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithTimeout(timeout time.Duration) *CustomerPrototypeApproveDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithContext(ctx context.Context) *CustomerPrototypeApproveDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithHTTPClient(client *http.Client) *CustomerPrototypeApproveDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithID(id string) *CustomerPrototypeApproveDevicesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetID(id string) {
	o.ID = id
}

// WithLocationID adds the locationID to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithLocationID(locationID string) *CustomerPrototypeApproveDevicesParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithMacs adds the macs to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithMacs(macs []models.XAny) *CustomerPrototypeApproveDevicesParams {
	o.SetMacs(macs)
	return o
}

// SetMacs adds the macs to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetMacs(macs []models.XAny) {
	o.Macs = macs
}

// WithNetworkID adds the networkID to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) WithNetworkID(networkID string) *CustomerPrototypeApproveDevicesParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the customer prototype approve devices params
func (o *CustomerPrototypeApproveDevicesParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPrototypeApproveDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}
	if o.Macs != nil {
		if err := r.SetBodyParam(o.Macs); err != nil {
			return err
		}
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
