// Code generated by go-swagger; DO NOT EDIT.

package node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// NodePrototypeUnclaimReader is a Reader for the NodePrototypeUnclaim structure.
type NodePrototypeUnclaimReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NodePrototypeUnclaimReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewNodePrototypeUnclaimNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNodePrototypeUnclaimDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNodePrototypeUnclaimNoContent creates a NodePrototypeUnclaimNoContent with default headers values
func NewNodePrototypeUnclaimNoContent() *NodePrototypeUnclaimNoContent {
	return &NodePrototypeUnclaimNoContent{}
}

/*
NodePrototypeUnclaimNoContent describes a response with status code 204, with default header values.

Request was successful
*/
type NodePrototypeUnclaimNoContent struct {
}

// IsSuccess returns true when this node prototype unclaim no content response has a 2xx status code
func (o *NodePrototypeUnclaimNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this node prototype unclaim no content response has a 3xx status code
func (o *NodePrototypeUnclaimNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this node prototype unclaim no content response has a 4xx status code
func (o *NodePrototypeUnclaimNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this node prototype unclaim no content response has a 5xx status code
func (o *NodePrototypeUnclaimNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this node prototype unclaim no content response a status code equal to that given
func (o *NodePrototypeUnclaimNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the node prototype unclaim no content response
func (o *NodePrototypeUnclaimNoContent) Code() int {
	return 204
}

func (o *NodePrototypeUnclaimNoContent) Error() string {
	return fmt.Sprintf("[DELETE /Nodes/{id}][%d] nodePrototypeUnclaimNoContent ", 204)
}

func (o *NodePrototypeUnclaimNoContent) String() string {
	return fmt.Sprintf("[DELETE /Nodes/{id}][%d] nodePrototypeUnclaimNoContent ", 204)
}

func (o *NodePrototypeUnclaimNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNodePrototypeUnclaimDefault creates a NodePrototypeUnclaimDefault with default headers values
func NewNodePrototypeUnclaimDefault(code int) *NodePrototypeUnclaimDefault {
	return &NodePrototypeUnclaimDefault{
		_statusCode: code,
	}
}

/*
NodePrototypeUnclaimDefault describes a response with status code -1, with default header values.

unexpected error
*/
type NodePrototypeUnclaimDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this node prototype unclaim default response has a 2xx status code
func (o *NodePrototypeUnclaimDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this node prototype unclaim default response has a 3xx status code
func (o *NodePrototypeUnclaimDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this node prototype unclaim default response has a 4xx status code
func (o *NodePrototypeUnclaimDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this node prototype unclaim default response has a 5xx status code
func (o *NodePrototypeUnclaimDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this node prototype unclaim default response a status code equal to that given
func (o *NodePrototypeUnclaimDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the node prototype unclaim default response
func (o *NodePrototypeUnclaimDefault) Code() int {
	return o._statusCode
}

func (o *NodePrototypeUnclaimDefault) Error() string {
	return fmt.Sprintf("[DELETE /Nodes/{id}][%d] Node.prototype.unclaim default  %+v", o._statusCode, o.Payload)
}

func (o *NodePrototypeUnclaimDefault) String() string {
	return fmt.Sprintf("[DELETE /Nodes/{id}][%d] Node.prototype.unclaim default  %+v", o._statusCode, o.Payload)
}

func (o *NodePrototypeUnclaimDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *NodePrototypeUnclaimDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
