// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLocationPrototypeGetGatewayAccountParams creates a new LocationPrototypeGetGatewayAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLocationPrototypeGetGatewayAccountParams() *LocationPrototypeGetGatewayAccountParams {
	return &LocationPrototypeGetGatewayAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLocationPrototypeGetGatewayAccountParamsWithTimeout creates a new LocationPrototypeGetGatewayAccountParams object
// with the ability to set a timeout on a request.
func NewLocationPrototypeGetGatewayAccountParamsWithTimeout(timeout time.Duration) *LocationPrototypeGetGatewayAccountParams {
	return &LocationPrototypeGetGatewayAccountParams{
		timeout: timeout,
	}
}

// NewLocationPrototypeGetGatewayAccountParamsWithContext creates a new LocationPrototypeGetGatewayAccountParams object
// with the ability to set a context for a request.
func NewLocationPrototypeGetGatewayAccountParamsWithContext(ctx context.Context) *LocationPrototypeGetGatewayAccountParams {
	return &LocationPrototypeGetGatewayAccountParams{
		Context: ctx,
	}
}

// NewLocationPrototypeGetGatewayAccountParamsWithHTTPClient creates a new LocationPrototypeGetGatewayAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewLocationPrototypeGetGatewayAccountParamsWithHTTPClient(client *http.Client) *LocationPrototypeGetGatewayAccountParams {
	return &LocationPrototypeGetGatewayAccountParams{
		HTTPClient: client,
	}
}

/*
LocationPrototypeGetGatewayAccountParams contains all the parameters to send to the API endpoint

	for the location prototype get gateway account operation.

	Typically these are written to a http.Request.
*/
type LocationPrototypeGetGatewayAccountParams struct {

	/* ID.

	   Location id

	   Format: JSON
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the location prototype get gateway account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LocationPrototypeGetGatewayAccountParams) WithDefaults() *LocationPrototypeGetGatewayAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the location prototype get gateway account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LocationPrototypeGetGatewayAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) WithTimeout(timeout time.Duration) *LocationPrototypeGetGatewayAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) WithContext(ctx context.Context) *LocationPrototypeGetGatewayAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) WithHTTPClient(client *http.Client) *LocationPrototypeGetGatewayAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) WithID(id string) *LocationPrototypeGetGatewayAccountParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the location prototype get gateway account params
func (o *LocationPrototypeGetGatewayAccountParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LocationPrototypeGetGatewayAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
