// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// LocationPrototypeClaimMultipleNodesReader is a Reader for the LocationPrototypeClaimMultipleNodes structure.
type LocationPrototypeClaimMultipleNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocationPrototypeClaimMultipleNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocationPrototypeClaimMultipleNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocationPrototypeClaimMultipleNodesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocationPrototypeClaimMultipleNodesOK creates a LocationPrototypeClaimMultipleNodesOK with default headers values
func NewLocationPrototypeClaimMultipleNodesOK() *LocationPrototypeClaimMultipleNodesOK {
	return &LocationPrototypeClaimMultipleNodesOK{}
}

/*
LocationPrototypeClaimMultipleNodesOK describes a response with status code 200, with default header values.

Request was successful
*/
type LocationPrototypeClaimMultipleNodesOK struct {
	Payload interface{}
}

// IsSuccess returns true when this location prototype claim multiple nodes o k response has a 2xx status code
func (o *LocationPrototypeClaimMultipleNodesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this location prototype claim multiple nodes o k response has a 3xx status code
func (o *LocationPrototypeClaimMultipleNodesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this location prototype claim multiple nodes o k response has a 4xx status code
func (o *LocationPrototypeClaimMultipleNodesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this location prototype claim multiple nodes o k response has a 5xx status code
func (o *LocationPrototypeClaimMultipleNodesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this location prototype claim multiple nodes o k response a status code equal to that given
func (o *LocationPrototypeClaimMultipleNodesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the location prototype claim multiple nodes o k response
func (o *LocationPrototypeClaimMultipleNodesOK) Code() int {
	return 200
}

func (o *LocationPrototypeClaimMultipleNodesOK) Error() string {
	return fmt.Sprintf("[POST /Locations/{id}/nodes][%d] locationPrototypeClaimMultipleNodesOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeClaimMultipleNodesOK) String() string {
	return fmt.Sprintf("[POST /Locations/{id}/nodes][%d] locationPrototypeClaimMultipleNodesOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeClaimMultipleNodesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *LocationPrototypeClaimMultipleNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLocationPrototypeClaimMultipleNodesDefault creates a LocationPrototypeClaimMultipleNodesDefault with default headers values
func NewLocationPrototypeClaimMultipleNodesDefault(code int) *LocationPrototypeClaimMultipleNodesDefault {
	return &LocationPrototypeClaimMultipleNodesDefault{
		_statusCode: code,
	}
}

/*
LocationPrototypeClaimMultipleNodesDefault describes a response with status code -1, with default header values.

unexpected error
*/
type LocationPrototypeClaimMultipleNodesDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this location prototype claim multiple nodes default response has a 2xx status code
func (o *LocationPrototypeClaimMultipleNodesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this location prototype claim multiple nodes default response has a 3xx status code
func (o *LocationPrototypeClaimMultipleNodesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this location prototype claim multiple nodes default response has a 4xx status code
func (o *LocationPrototypeClaimMultipleNodesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this location prototype claim multiple nodes default response has a 5xx status code
func (o *LocationPrototypeClaimMultipleNodesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this location prototype claim multiple nodes default response a status code equal to that given
func (o *LocationPrototypeClaimMultipleNodesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the location prototype claim multiple nodes default response
func (o *LocationPrototypeClaimMultipleNodesDefault) Code() int {
	return o._statusCode
}

func (o *LocationPrototypeClaimMultipleNodesDefault) Error() string {
	return fmt.Sprintf("[POST /Locations/{id}/nodes][%d] Location.prototype.claimMultipleNodes default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeClaimMultipleNodesDefault) String() string {
	return fmt.Sprintf("[POST /Locations/{id}/nodes][%d] Location.prototype.claimMultipleNodes default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeClaimMultipleNodesDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *LocationPrototypeClaimMultipleNodesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
