// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// LocationPrototypeGetInvitationsReader is a Reader for the LocationPrototypeGetInvitations structure.
type LocationPrototypeGetInvitationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocationPrototypeGetInvitationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocationPrototypeGetInvitationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocationPrototypeGetInvitationsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocationPrototypeGetInvitationsOK creates a LocationPrototypeGetInvitationsOK with default headers values
func NewLocationPrototypeGetInvitationsOK() *LocationPrototypeGetInvitationsOK {
	return &LocationPrototypeGetInvitationsOK{}
}

/*
LocationPrototypeGetInvitationsOK describes a response with status code 200, with default header values.

Request was successful
*/
type LocationPrototypeGetInvitationsOK struct {
	Payload []*models.Invitation
}

// IsSuccess returns true when this location prototype get invitations o k response has a 2xx status code
func (o *LocationPrototypeGetInvitationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this location prototype get invitations o k response has a 3xx status code
func (o *LocationPrototypeGetInvitationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this location prototype get invitations o k response has a 4xx status code
func (o *LocationPrototypeGetInvitationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this location prototype get invitations o k response has a 5xx status code
func (o *LocationPrototypeGetInvitationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this location prototype get invitations o k response a status code equal to that given
func (o *LocationPrototypeGetInvitationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the location prototype get invitations o k response
func (o *LocationPrototypeGetInvitationsOK) Code() int {
	return 200
}

func (o *LocationPrototypeGetInvitationsOK) Error() string {
	return fmt.Sprintf("[GET /Locations/{id}/invitations][%d] locationPrototypeGetInvitationsOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeGetInvitationsOK) String() string {
	return fmt.Sprintf("[GET /Locations/{id}/invitations][%d] locationPrototypeGetInvitationsOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeGetInvitationsOK) GetPayload() []*models.Invitation {
	return o.Payload
}

func (o *LocationPrototypeGetInvitationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLocationPrototypeGetInvitationsDefault creates a LocationPrototypeGetInvitationsDefault with default headers values
func NewLocationPrototypeGetInvitationsDefault(code int) *LocationPrototypeGetInvitationsDefault {
	return &LocationPrototypeGetInvitationsDefault{
		_statusCode: code,
	}
}

/*
LocationPrototypeGetInvitationsDefault describes a response with status code -1, with default header values.

unexpected error
*/
type LocationPrototypeGetInvitationsDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this location prototype get invitations default response has a 2xx status code
func (o *LocationPrototypeGetInvitationsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this location prototype get invitations default response has a 3xx status code
func (o *LocationPrototypeGetInvitationsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this location prototype get invitations default response has a 4xx status code
func (o *LocationPrototypeGetInvitationsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this location prototype get invitations default response has a 5xx status code
func (o *LocationPrototypeGetInvitationsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this location prototype get invitations default response a status code equal to that given
func (o *LocationPrototypeGetInvitationsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the location prototype get invitations default response
func (o *LocationPrototypeGetInvitationsDefault) Code() int {
	return o._statusCode
}

func (o *LocationPrototypeGetInvitationsDefault) Error() string {
	return fmt.Sprintf("[GET /Locations/{id}/invitations][%d] Location.prototype.__get__invitations default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeGetInvitationsDefault) String() string {
	return fmt.Sprintf("[GET /Locations/{id}/invitations][%d] Location.prototype.__get__invitations default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeGetInvitationsDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *LocationPrototypeGetInvitationsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
