// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacReader is a Reader for the LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMac structure.
type LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK creates a LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK with default headers values
func NewLocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK() *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK {
	return &LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK{}
}

/*
LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK describes a response with status code 200, with default header values.

Request was successful
*/
type LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK struct {
	Payload interface{}
}

// IsSuccess returns true when this location prototype find room by node Id node mac and device mac o k response has a 2xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this location prototype find room by node Id node mac and device mac o k response has a 3xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this location prototype find room by node Id node mac and device mac o k response has a 4xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this location prototype find room by node Id node mac and device mac o k response has a 5xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) IsServerError() bool {
	return false
}

// IsCode returns true when this location prototype find room by node Id node mac and device mac o k response a status code equal to that given
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the location prototype find room by node Id node mac and device mac o k response
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) Code() int {
	return 200
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) Error() string {
	return fmt.Sprintf("[GET /Locations/{id}/rooms/search/{search}][%d] locationPrototypeFindRoomByNodeIdNodeMacAndDeviceMacOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) String() string {
	return fmt.Sprintf("[GET /Locations/{id}/rooms/search/{search}][%d] locationPrototypeFindRoomByNodeIdNodeMacAndDeviceMacOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) GetPayload() interface{} {
	return o.Payload
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault creates a LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault with default headers values
func NewLocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault(code int) *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault {
	return &LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault{
		_statusCode: code,
	}
}

/*
LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault describes a response with status code -1, with default header values.

unexpected error
*/
type LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this location prototype find room by node Id node mac and device mac default response has a 2xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this location prototype find room by node Id node mac and device mac default response has a 3xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this location prototype find room by node Id node mac and device mac default response has a 4xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this location prototype find room by node Id node mac and device mac default response has a 5xx status code
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this location prototype find room by node Id node mac and device mac default response a status code equal to that given
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the location prototype find room by node Id node mac and device mac default response
func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) Code() int {
	return o._statusCode
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) Error() string {
	return fmt.Sprintf("[GET /Locations/{id}/rooms/search/{search}][%d] Location.prototype.findRoomByNodeIdNodeMacAndDeviceMac default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) String() string {
	return fmt.Sprintf("[GET /Locations/{id}/rooms/search/{search}][%d] Location.prototype.findRoomByNodeIdNodeMacAndDeviceMac default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *LocationPrototypeFindRoomByNodeIDNodeMacAndDeviceMacDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
