// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// LocationPrototypeGetHomeAwayConfigReader is a Reader for the LocationPrototypeGetHomeAwayConfig structure.
type LocationPrototypeGetHomeAwayConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocationPrototypeGetHomeAwayConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocationPrototypeGetHomeAwayConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocationPrototypeGetHomeAwayConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocationPrototypeGetHomeAwayConfigOK creates a LocationPrototypeGetHomeAwayConfigOK with default headers values
func NewLocationPrototypeGetHomeAwayConfigOK() *LocationPrototypeGetHomeAwayConfigOK {
	return &LocationPrototypeGetHomeAwayConfigOK{}
}

/*
LocationPrototypeGetHomeAwayConfigOK describes a response with status code 200, with default header values.

Request was successful
*/
type LocationPrototypeGetHomeAwayConfigOK struct {
	Payload interface{}
}

// IsSuccess returns true when this location prototype get home away config o k response has a 2xx status code
func (o *LocationPrototypeGetHomeAwayConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this location prototype get home away config o k response has a 3xx status code
func (o *LocationPrototypeGetHomeAwayConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this location prototype get home away config o k response has a 4xx status code
func (o *LocationPrototypeGetHomeAwayConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this location prototype get home away config o k response has a 5xx status code
func (o *LocationPrototypeGetHomeAwayConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this location prototype get home away config o k response a status code equal to that given
func (o *LocationPrototypeGetHomeAwayConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the location prototype get home away config o k response
func (o *LocationPrototypeGetHomeAwayConfigOK) Code() int {
	return 200
}

func (o *LocationPrototypeGetHomeAwayConfigOK) Error() string {
	return fmt.Sprintf("[GET /Locations/{id}/homeAway][%d] locationPrototypeGetHomeAwayConfigOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeGetHomeAwayConfigOK) String() string {
	return fmt.Sprintf("[GET /Locations/{id}/homeAway][%d] locationPrototypeGetHomeAwayConfigOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypeGetHomeAwayConfigOK) GetPayload() interface{} {
	return o.Payload
}

func (o *LocationPrototypeGetHomeAwayConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLocationPrototypeGetHomeAwayConfigDefault creates a LocationPrototypeGetHomeAwayConfigDefault with default headers values
func NewLocationPrototypeGetHomeAwayConfigDefault(code int) *LocationPrototypeGetHomeAwayConfigDefault {
	return &LocationPrototypeGetHomeAwayConfigDefault{
		_statusCode: code,
	}
}

/*
LocationPrototypeGetHomeAwayConfigDefault describes a response with status code -1, with default header values.

unexpected error
*/
type LocationPrototypeGetHomeAwayConfigDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this location prototype get home away config default response has a 2xx status code
func (o *LocationPrototypeGetHomeAwayConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this location prototype get home away config default response has a 3xx status code
func (o *LocationPrototypeGetHomeAwayConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this location prototype get home away config default response has a 4xx status code
func (o *LocationPrototypeGetHomeAwayConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this location prototype get home away config default response has a 5xx status code
func (o *LocationPrototypeGetHomeAwayConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this location prototype get home away config default response a status code equal to that given
func (o *LocationPrototypeGetHomeAwayConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the location prototype get home away config default response
func (o *LocationPrototypeGetHomeAwayConfigDefault) Code() int {
	return o._statusCode
}

func (o *LocationPrototypeGetHomeAwayConfigDefault) Error() string {
	return fmt.Sprintf("[GET /Locations/{id}/homeAway][%d] Location.prototype.getHomeAwayConfig default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeGetHomeAwayConfigDefault) String() string {
	return fmt.Sprintf("[GET /Locations/{id}/homeAway][%d] Location.prototype.getHomeAwayConfig default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypeGetHomeAwayConfigDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *LocationPrototypeGetHomeAwayConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
