// Code generated by go-swagger; DO NOT EDIT.

package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// LocationPrototypePatchHomeSecuritySensitivityReader is a Reader for the LocationPrototypePatchHomeSecuritySensitivity structure.
type LocationPrototypePatchHomeSecuritySensitivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LocationPrototypePatchHomeSecuritySensitivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLocationPrototypePatchHomeSecuritySensitivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewLocationPrototypePatchHomeSecuritySensitivityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewLocationPrototypePatchHomeSecuritySensitivityOK creates a LocationPrototypePatchHomeSecuritySensitivityOK with default headers values
func NewLocationPrototypePatchHomeSecuritySensitivityOK() *LocationPrototypePatchHomeSecuritySensitivityOK {
	return &LocationPrototypePatchHomeSecuritySensitivityOK{}
}

/*
LocationPrototypePatchHomeSecuritySensitivityOK describes a response with status code 200, with default header values.

Request was successful
*/
type LocationPrototypePatchHomeSecuritySensitivityOK struct {
	Payload *models.HomeSecurity
}

// IsSuccess returns true when this location prototype patch home security sensitivity o k response has a 2xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this location prototype patch home security sensitivity o k response has a 3xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this location prototype patch home security sensitivity o k response has a 4xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this location prototype patch home security sensitivity o k response has a 5xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this location prototype patch home security sensitivity o k response a status code equal to that given
func (o *LocationPrototypePatchHomeSecuritySensitivityOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the location prototype patch home security sensitivity o k response
func (o *LocationPrototypePatchHomeSecuritySensitivityOK) Code() int {
	return 200
}

func (o *LocationPrototypePatchHomeSecuritySensitivityOK) Error() string {
	return fmt.Sprintf("[PATCH /Locations/{id}/homeSecurity/sensitivity][%d] locationPrototypePatchHomeSecuritySensitivityOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypePatchHomeSecuritySensitivityOK) String() string {
	return fmt.Sprintf("[PATCH /Locations/{id}/homeSecurity/sensitivity][%d] locationPrototypePatchHomeSecuritySensitivityOK  %+v", 200, o.Payload)
}

func (o *LocationPrototypePatchHomeSecuritySensitivityOK) GetPayload() *models.HomeSecurity {
	return o.Payload
}

func (o *LocationPrototypePatchHomeSecuritySensitivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HomeSecurity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLocationPrototypePatchHomeSecuritySensitivityDefault creates a LocationPrototypePatchHomeSecuritySensitivityDefault with default headers values
func NewLocationPrototypePatchHomeSecuritySensitivityDefault(code int) *LocationPrototypePatchHomeSecuritySensitivityDefault {
	return &LocationPrototypePatchHomeSecuritySensitivityDefault{
		_statusCode: code,
	}
}

/*
LocationPrototypePatchHomeSecuritySensitivityDefault describes a response with status code -1, with default header values.

unexpected error
*/
type LocationPrototypePatchHomeSecuritySensitivityDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this location prototype patch home security sensitivity default response has a 2xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this location prototype patch home security sensitivity default response has a 3xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this location prototype patch home security sensitivity default response has a 4xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this location prototype patch home security sensitivity default response has a 5xx status code
func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this location prototype patch home security sensitivity default response a status code equal to that given
func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the location prototype patch home security sensitivity default response
func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) Code() int {
	return o._statusCode
}

func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) Error() string {
	return fmt.Sprintf("[PATCH /Locations/{id}/homeSecurity/sensitivity][%d] Location.prototype.patchHomeSecuritySensitivity default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) String() string {
	return fmt.Sprintf("[PATCH /Locations/{id}/homeSecurity/sensitivity][%d] Location.prototype.patchHomeSecuritySensitivity default  %+v", o._statusCode, o.Payload)
}

func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *LocationPrototypePatchHomeSecuritySensitivityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
