/*
 * plume-customer
 *
 * Customer APIs for NOC, IOS, Android, QA scripts, and www.plume.com
 *
 * API version: 1.109.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DnsServers struct {
	PrimaryDns string `json:"primaryDns,omitempty"`
	Enabled bool `json:"enabled"`
	SecondaryDns string `json:"secondaryDns,omitempty"`
}
