/*
 * plume-customer
 *
 * Customer APIs for NOC, IOS, Android, QA scripts, and www.plume.com
 *
 * API version: 1.109.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type OnboardingCheckpoint struct {
	Value string `json:"value"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Id *ObjectId `json:"id,omitempty"`
	LocationId *ObjectId `json:"locationId,omitempty"`
}
