// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGroupFindParams creates a new GroupFindParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupFindParams() *GroupFindParams {
	return &GroupFindParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupFindParamsWithTimeout creates a new GroupFindParams object
// with the ability to set a timeout on a request.
func NewGroupFindParamsWithTimeout(timeout time.Duration) *GroupFindParams {
	return &GroupFindParams{
		timeout: timeout,
	}
}

// NewGroupFindParamsWithContext creates a new GroupFindParams object
// with the ability to set a context for a request.
func NewGroupFindParamsWithContext(ctx context.Context) *GroupFindParams {
	return &GroupFindParams{
		Context: ctx,
	}
}

// NewGroupFindParamsWithHTTPClient creates a new GroupFindParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupFindParamsWithHTTPClient(client *http.Client) *GroupFindParams {
	return &GroupFindParams{
		HTTPClient: client,
	}
}

/*
GroupFindParams contains all the parameters to send to the API endpoint

	for the group find operation.

	Typically these are written to a http.Request.
*/
type GroupFindParams struct {

	/* Filter.

	   Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string (`{"where":{"something":"value"}}`).  See https://loopback.io/doc/en/lb3/Querying-data.html#using-stringified-json-in-rest-queries for more details.

	   Format: JSON
	*/
	Filter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the group find params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupFindParams) WithDefaults() *GroupFindParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the group find params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupFindParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the group find params
func (o *GroupFindParams) WithTimeout(timeout time.Duration) *GroupFindParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the group find params
func (o *GroupFindParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the group find params
func (o *GroupFindParams) WithContext(ctx context.Context) *GroupFindParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the group find params
func (o *GroupFindParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the group find params
func (o *GroupFindParams) WithHTTPClient(client *http.Client) *GroupFindParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the group find params
func (o *GroupFindParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the group find params
func (o *GroupFindParams) WithFilter(filter *string) *GroupFindParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the group find params
func (o *GroupFindParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WriteToRequest writes these params to a swagger request
func (o *GroupFindParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
