// Code generated by go-swagger; DO NOT EDIT.

package partner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPartnerGetCustomerCountParams creates a new PartnerGetCustomerCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPartnerGetCustomerCountParams() *PartnerGetCustomerCountParams {
	return &PartnerGetCustomerCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPartnerGetCustomerCountParamsWithTimeout creates a new PartnerGetCustomerCountParams object
// with the ability to set a timeout on a request.
func NewPartnerGetCustomerCountParamsWithTimeout(timeout time.Duration) *PartnerGetCustomerCountParams {
	return &PartnerGetCustomerCountParams{
		timeout: timeout,
	}
}

// NewPartnerGetCustomerCountParamsWithContext creates a new PartnerGetCustomerCountParams object
// with the ability to set a context for a request.
func NewPartnerGetCustomerCountParamsWithContext(ctx context.Context) *PartnerGetCustomerCountParams {
	return &PartnerGetCustomerCountParams{
		Context: ctx,
	}
}

// NewPartnerGetCustomerCountParamsWithHTTPClient creates a new PartnerGetCustomerCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPartnerGetCustomerCountParamsWithHTTPClient(client *http.Client) *PartnerGetCustomerCountParams {
	return &PartnerGetCustomerCountParams{
		HTTPClient: client,
	}
}

/*
PartnerGetCustomerCountParams contains all the parameters to send to the API endpoint

	for the partner get customer count operation.

	Typically these are written to a http.Request.
*/
type PartnerGetCustomerCountParams struct {

	/* ID.

	   partner Id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the partner get customer count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PartnerGetCustomerCountParams) WithDefaults() *PartnerGetCustomerCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the partner get customer count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PartnerGetCustomerCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the partner get customer count params
func (o *PartnerGetCustomerCountParams) WithTimeout(timeout time.Duration) *PartnerGetCustomerCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the partner get customer count params
func (o *PartnerGetCustomerCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the partner get customer count params
func (o *PartnerGetCustomerCountParams) WithContext(ctx context.Context) *PartnerGetCustomerCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the partner get customer count params
func (o *PartnerGetCustomerCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the partner get customer count params
func (o *PartnerGetCustomerCountParams) WithHTTPClient(client *http.Client) *PartnerGetCustomerCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the partner get customer count params
func (o *PartnerGetCustomerCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the partner get customer count params
func (o *PartnerGetCustomerCountParams) WithID(id string) *PartnerGetCustomerCountParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the partner get customer count params
func (o *PartnerGetCustomerCountParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PartnerGetCustomerCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
