// Code generated by go-swagger; DO NOT EDIT.

package partner_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPartnerConfigGetVlanServicesParams creates a new PartnerConfigGetVlanServicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPartnerConfigGetVlanServicesParams() *PartnerConfigGetVlanServicesParams {
	return &PartnerConfigGetVlanServicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPartnerConfigGetVlanServicesParamsWithTimeout creates a new PartnerConfigGetVlanServicesParams object
// with the ability to set a timeout on a request.
func NewPartnerConfigGetVlanServicesParamsWithTimeout(timeout time.Duration) *PartnerConfigGetVlanServicesParams {
	return &PartnerConfigGetVlanServicesParams{
		timeout: timeout,
	}
}

// NewPartnerConfigGetVlanServicesParamsWithContext creates a new PartnerConfigGetVlanServicesParams object
// with the ability to set a context for a request.
func NewPartnerConfigGetVlanServicesParamsWithContext(ctx context.Context) *PartnerConfigGetVlanServicesParams {
	return &PartnerConfigGetVlanServicesParams{
		Context: ctx,
	}
}

// NewPartnerConfigGetVlanServicesParamsWithHTTPClient creates a new PartnerConfigGetVlanServicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPartnerConfigGetVlanServicesParamsWithHTTPClient(client *http.Client) *PartnerConfigGetVlanServicesParams {
	return &PartnerConfigGetVlanServicesParams{
		HTTPClient: client,
	}
}

/*
PartnerConfigGetVlanServicesParams contains all the parameters to send to the API endpoint

	for the partner config get vlan services operation.

	Typically these are written to a http.Request.
*/
type PartnerConfigGetVlanServicesParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the partner config get vlan services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PartnerConfigGetVlanServicesParams) WithDefaults() *PartnerConfigGetVlanServicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the partner config get vlan services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PartnerConfigGetVlanServicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) WithTimeout(timeout time.Duration) *PartnerConfigGetVlanServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) WithContext(ctx context.Context) *PartnerConfigGetVlanServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) WithHTTPClient(client *http.Client) *PartnerConfigGetVlanServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) WithID(id string) *PartnerConfigGetVlanServicesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the partner config get vlan services params
func (o *PartnerConfigGetVlanServicesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PartnerConfigGetVlanServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
