// Code generated by go-swagger; DO NOT EDIT.

package partner_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/binarycraft007/opensync-api/models"
)

// PartnerConfigGetAppEngagementTimerConfigReader is a Reader for the PartnerConfigGetAppEngagementTimerConfig structure.
type PartnerConfigGetAppEngagementTimerConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PartnerConfigGetAppEngagementTimerConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPartnerConfigGetAppEngagementTimerConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPartnerConfigGetAppEngagementTimerConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPartnerConfigGetAppEngagementTimerConfigOK creates a PartnerConfigGetAppEngagementTimerConfigOK with default headers values
func NewPartnerConfigGetAppEngagementTimerConfigOK() *PartnerConfigGetAppEngagementTimerConfigOK {
	return &PartnerConfigGetAppEngagementTimerConfigOK{}
}

/*
PartnerConfigGetAppEngagementTimerConfigOK describes a response with status code 200, with default header values.

Request was successful
*/
type PartnerConfigGetAppEngagementTimerConfigOK struct {
	Payload models.XAny
}

// IsSuccess returns true when this partner config get app engagement timer config o k response has a 2xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this partner config get app engagement timer config o k response has a 3xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this partner config get app engagement timer config o k response has a 4xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this partner config get app engagement timer config o k response has a 5xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this partner config get app engagement timer config o k response a status code equal to that given
func (o *PartnerConfigGetAppEngagementTimerConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the partner config get app engagement timer config o k response
func (o *PartnerConfigGetAppEngagementTimerConfigOK) Code() int {
	return 200
}

func (o *PartnerConfigGetAppEngagementTimerConfigOK) Error() string {
	return fmt.Sprintf("[GET /partnerConfig/{id}/appEngagementTimer][%d] partnerConfigGetAppEngagementTimerConfigOK  %+v", 200, o.Payload)
}

func (o *PartnerConfigGetAppEngagementTimerConfigOK) String() string {
	return fmt.Sprintf("[GET /partnerConfig/{id}/appEngagementTimer][%d] partnerConfigGetAppEngagementTimerConfigOK  %+v", 200, o.Payload)
}

func (o *PartnerConfigGetAppEngagementTimerConfigOK) GetPayload() models.XAny {
	return o.Payload
}

func (o *PartnerConfigGetAppEngagementTimerConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartnerConfigGetAppEngagementTimerConfigDefault creates a PartnerConfigGetAppEngagementTimerConfigDefault with default headers values
func NewPartnerConfigGetAppEngagementTimerConfigDefault(code int) *PartnerConfigGetAppEngagementTimerConfigDefault {
	return &PartnerConfigGetAppEngagementTimerConfigDefault{
		_statusCode: code,
	}
}

/*
PartnerConfigGetAppEngagementTimerConfigDefault describes a response with status code -1, with default header values.

unexpected error
*/
type PartnerConfigGetAppEngagementTimerConfigDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// IsSuccess returns true when this partner config get app engagement timer config default response has a 2xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this partner config get app engagement timer config default response has a 3xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this partner config get app engagement timer config default response has a 4xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this partner config get app engagement timer config default response has a 5xx status code
func (o *PartnerConfigGetAppEngagementTimerConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this partner config get app engagement timer config default response a status code equal to that given
func (o *PartnerConfigGetAppEngagementTimerConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the partner config get app engagement timer config default response
func (o *PartnerConfigGetAppEngagementTimerConfigDefault) Code() int {
	return o._statusCode
}

func (o *PartnerConfigGetAppEngagementTimerConfigDefault) Error() string {
	return fmt.Sprintf("[GET /partnerConfig/{id}/appEngagementTimer][%d] PartnerConfig.getAppEngagementTimerConfig default  %+v", o._statusCode, o.Payload)
}

func (o *PartnerConfigGetAppEngagementTimerConfigDefault) String() string {
	return fmt.Sprintf("[GET /partnerConfig/{id}/appEngagementTimer][%d] PartnerConfig.getAppEngagementTimerConfig default  %+v", o._statusCode, o.Payload)
}

func (o *PartnerConfigGetAppEngagementTimerConfigDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *PartnerConfigGetAppEngagementTimerConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
